version: '{build}'
image: Visual Studio 2019
configuration: Release

before_build:
- cmd: dotnet restore

artifacts:
  - path: '**\*.nupkg'
  
deploy:
- provider: NuGet
  api_key:
    secure: x6Qtht6EqnrMnwvUCCiTcewdgCsKXM63vHDcmtvZ8KweHN4iIVtexIuKBSfZf9QF
  on:
    appveyor_repo_tag: true
